// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU6raWJPYoJCarWh9f2hbGn_2TOlDsIuw',
    appId: '1:1072672814476:web:ffeb8b501409ada77f52a9',
    messagingSenderId: '1072672814476',
    projectId: 'e-learning-a6dc0',
    authDomain: 'e-learning-a6dc0.firebaseapp.com',
    storageBucket: 'e-learning-a6dc0.appspot.com',
    measurementId: 'G-5SZBS2NRWK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWT_01hdFi7fY-SBPevnFAumHKOWK8eXQ',
    appId: '1:1072672814476:android:bfe95948d9acdd8a7f52a9',
    messagingSenderId: '1072672814476',
    projectId: 'e-learning-a6dc0',
    storageBucket: 'e-learning-a6dc0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6EnGwJT6F29AG3bfXory7GIqcKypK-8Y',
    appId: '1:1072672814476:ios:a2a653514d15811b7f52a9',
    messagingSenderId: '1072672814476',
    projectId: 'e-learning-a6dc0',
    storageBucket: 'e-learning-a6dc0.appspot.com',
    iosClientId: '1072672814476-qi15svq0sde8n4jb60n7tcmvu70t8g55.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6EnGwJT6F29AG3bfXory7GIqcKypK-8Y',
    appId: '1:1072672814476:ios:a2a653514d15811b7f52a9',
    messagingSenderId: '1072672814476',
    projectId: 'e-learning-a6dc0',
    storageBucket: 'e-learning-a6dc0.appspot.com',
    iosClientId: '1072672814476-qi15svq0sde8n4jb60n7tcmvu70t8g55.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDU6raWJPYoJCarWh9f2hbGn_2TOlDsIuw',
    appId: '1:1072672814476:web:f7652a6fd138846f7f52a9',
    messagingSenderId: '1072672814476',
    projectId: 'e-learning-a6dc0',
    authDomain: 'e-learning-a6dc0.firebaseapp.com',
    storageBucket: 'e-learning-a6dc0.appspot.com',
    measurementId: 'G-FQEES9NGM3',
  );
}
